services:
  pantilt:
    build: .
    container_name: pantilt_ros2
    network_mode: host
    ipc: host
    privileged: true

    volumes:
      - ./src:/ros2_ws/src
      - /dev:/dev

    environment:
      - ROS_DOMAIN_ID=0

    tty: true
    stdin_open: true
